### ISSUE TITLE
Esc keyboard feature

### ISSUE THREAD

**Issue by renatonascalves** [danklammer/microlite#1]
While testing [here](http://output.jsbin.com/vopoba/), I noticed it is not possible to go back clicking on the esc keyboard.

That would be a nice addition.

**Comment by danklammer** [comment]
@renatonascalves I agree!

**Comment by i-a-n** [comment]
just a note; I've implemented this on my fork: https://github.com/i-a-n/microlite-esc

still working on compressing the code further if possible, but I can open a PR if you'd like to merge it, @danklammer

**Comment by danklammer** [comment]
@i-a-n I dig it! Open a PR and I'll merge it in!

**Comment by danklammer** [comment]
Closed thanks to @i-a-n! 🙌

See PR #3
